module VerifyExamples.Action.Exiting0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Action exposing (..)
import Task







spec0 : Test.Test
spec0 =
    Test.test "#exiting: \n\n    exiting\n    |> Action.config\n    |> Action.withExit ((42,0),Cmd.none)\n    |> Action.apply\n    |> Tuple.first\n    --> (42,0)" <|
        \() ->
            Expect.equal
                (
                exiting
                |> Action.config
                |> Action.withExit ((42,0),Cmd.none)
                |> Action.apply
                |> Tuple.first
                )
                (
                (42,0)
                )