module VerifyExamples.Action.Updating0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Action exposing (..)
import Task







spec0 : Test.Test
spec0 =
    Test.test "#updating: \n\n    updating (42, Cmd.none)\n    |> Action.config\n    |> Action.withUpdate (\\int -> (int,0)) never\n    |> Action.apply\n    |> Tuple.first\n    --> (42,0)" <|
        \() ->
            Expect.equal
                (
                updating (42, Cmd.none)
                |> Action.config
                |> Action.withUpdate (\int -> (int,0)) never
                |> Action.apply
                |> Tuple.first
                )
                (
                (42,0)
                )